### ISSUE TITLE
implement session monitoring .NET

### ISSUE THREAD

**Issue by PK1NONLY** [opentok/Opentok-.NET-SDK#121]
i am trying to implement session monitoring using .net,
i can see the option for configure callback url, but icannot find any example for callback url,
can i a sample for callback url ?? how it should look like??

**Comment by msach22** [comment]
At this time, OpenTok don't support configuring callbacks via the REST API or the Server SDKs. You can only do that through the account dashboard: https://tokbox.com/account

**Comment by PK1NONLY** [comment]
hi thanks for reply can you  please give an example how can i write the call back url using .NET,
the configuration of the call back url is given the documentation, but i cannot find any example or sample project for creating the call back url

**Comment by msach22** [comment]
@PK1NONLY Setting up the callback is dependent on your application server and the libraries you use. Unfortunately, I'm unable to help with that since it's application logic. You would need to set a path and configure that within the TokBox Dashboard. You would also need to make sure that the server is reachable and not just running on localhost.
