### ISSUE TITLE
How does the scheduled meetings work?

### ISSUE THREAD

**Issue by prabhakarreddy1234** [opentok/Opentok-.NET-SDK#85]
If i want to schedule a group video conference in the future date then when does the session gets created or how to make sure all participants joins same session ? Is it that session will be created when a conference is scheduled but token will be generated when the users start joining the conference. Any sample code would be nice.

**Comment by aullman** [comment]
You can create a session with the server SDK at any time. Servers will not be provisioned for that session until the first participant joins. So you can create sessions up front for meetings you know will happen in the future. Then when it's time for people to join the session, that's when you should generate a token for them, because the tokens will expire.
